### PR TITLE
feat(CrossCompile): Added cross compiling

### PR DESCRIPTION
**Pull request by AlexsJones**
Hello 👋 first contribution, great project.

- Ran a `go fmt` to tidy indentation
- Created new cross-compiled build artefacts.
POW:
```
make
go mod vendor;
go fmt ./...;
mkdir -p build;
GOFLAGS=-mod=vendor gox -ldflags "-s -w" --osarch="linux/amd64" --osarch="windows/amd64" --osarch="darwin/amd64" -output "build/kubeletctl_{{.OS}}_{{.Arch}}"
Number of parallel builds: 5

-->    darwin/amd64: kubeletctl
-->   windows/amd64: kubeletctl
-->     linux/amd64: kubeletctl
```

- Introduced Makefile to hold build commands as versioning will eventually want to added in ( and more complex docker builds) 

I hope this is useful. Thanks

Signed-off-by: AlexsJones <alexsimonjones@gmail.com>

### CODE REVIEW

**Comment by AlexsJones** [comment]
Hey @g3rzi , let me know if there is anything else you'd like me to do like sign a contributor agreement?

Otherwise I have another PR behind this to help with the Dockerfile.

**Comment by g3rzi** [comment]
Hi @AlexsJones thank you very much for your contribution! :)
I checked what you did, looks great.

Regarding the building note in the readme, you removed:
```
gox -ldflags "-s -w" 
```

I am going to add it back but with more systems:
```
gox -ldflags "-s -w" -osarch linux/amd64 -osarch linux/386 -osarch windows/amd64 -osarch windows/386
```

This is because the Make file is a great way for building but for users that use Windows system it will be more comfortable to use the `gox` directly.
I just want to compile it and test it before I will merge and let you know.

Regarding the signing a contributor agreement, I am not familiar with this, can you give me a link for explanation about it that I can understand what it means?

**Comment by AlexsJones** [comment]
Thanks for the comments and the updates @g3rzi 

The contributor agreement is probably not necessary but on some larger projects like Kubernetes they keep a manifest of contributors who have signed an agreement to be a part of that community https://github.com/cla-assistant/cla-assistant 

This is a great project and I am excited to use it more! :)

**Comment by g3rzi** [comment]
Thank you! :)

I happy to hear that and really appreciate your contribution, it helps a lot. This is what I like on open source projects :)

I will read about the contribution agreement, there other stuff that I had in my mind but not have time from them like writing testing, other small features, etc.

This is a small project so it is less critical but these are important things to add.

**Pull request merged**
